Repository hassio-addons/addon-tautulli, pull requests merged in 2023-03, with the labels that each got.

#278 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  tautulli/.README.j2
  tautulli/DOCS.md
Labels: maintenance

#280 ⬆️ Upgrades Tautulli to v2.12.0
  tautulli/Dockerfile
Labels: dependencies

#281 ⬆️ Upgrades Tautulli to v2.12.1
  tautulli/Dockerfile
Labels: dependencies

#282 ⬆️ Upgrades Tautulli to v2.12.2
  tautulli/Dockerfile
Labels: dependencies

#283 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  tautulli/Dockerfile
Labels: maintenance

#287 Fix the Tautulli version not being set up as env variable
  .github/renovate.json
  tautulli/Dockerfile
Labels: bugfix

#288 Fix broken URL
  tautulli/DOCS.md
Labels: documentation
